#!/usr/bin/python3
"""
Stub D-Bus service for Ubuntu Advantage.

This minimal service replaces the real ubuntu-advantage-tools D-Bus service
to prevent crashes in GUI applications that depend on it.
"""

import sys
import syslog
import dbus
import dbus.service
import dbus.mainloop.glib
from gi.repository import GLib


class UbuntuAdvantageObjectManager(dbus.service.Object):
    """Stub ObjectManager at root path."""
    
    def __init__(self, bus_name):
        dbus.service.Object.__init__(self, bus_name, '/')
    
    @dbus.service.method('org.freedesktop.DBus.ObjectManager',
                         out_signature='a{oa{sa{sv}}}')
    def GetManagedObjects(self):
        """Return empty managed objects dict."""
        syslog.syslog(syslog.LOG_DEBUG, "GetManagedObjects called on root path")
        return dbus.Dictionary({}, signature='oa{sa{sv}}')


class UbuntuAdvantageManager(dbus.service.Object):
    """Stub D-Bus service that mimics Ubuntu Advantage Manager."""
    
    def __init__(self, bus_name):
        dbus.service.Object.__init__(self, bus_name, '/com/canonical/UbuntuAdvantage/Manager')
    
    @dbus.service.method('org.freedesktop.DBus.ObjectManager',
                         out_signature='a{oa{sa{sv}}}')
    def GetManagedObjects(self):
        """Return empty managed objects dict."""
        syslog.syslog(syslog.LOG_DEBUG, "GetManagedObjects called on Manager path")
        return dbus.Dictionary({}, signature='oa{sa{sv}}')
    
    @dbus.service.method('com.canonical.UbuntuAdvantage.Manager',
                         in_signature='s', out_signature='')
    def Attach(self, token):
        """Stub method for attaching to Ubuntu Pro."""
        syslog.syslog(syslog.LOG_DEBUG, "Attach called")
        raise dbus.exceptions.DBusException(
            'Ubuntu Advantage not available',
            name='com.canonical.UbuntuAdvantage.Error.NotAvailable'
        )
    
    @dbus.service.method('com.canonical.UbuntuAdvantage.Manager',
                         in_signature='', out_signature='')
    def Detach(self):
        """Stub method for detaching from Ubuntu Pro."""
        syslog.syslog(syslog.LOG_DEBUG, "Detach called")
        raise dbus.exceptions.DBusException(
            'Ubuntu Advantage not available',
            name='com.canonical.UbuntuAdvantage.Error.NotAvailable'
        )
    
    @dbus.service.method('com.canonical.UbuntuAdvantage.Manager',
                         in_signature='', out_signature='s')
    def GetStatus(self):
        """Stub method that returns unattached status."""
        syslog.syslog(syslog.LOG_DEBUG, "GetStatus called")
        import json
        return json.dumps({
            'attached': False,
            'enabled_services': [],
            'available_services': []
        })
    
    @dbus.service.method('org.freedesktop.DBus.Introspectable',
                         out_signature='s')
    def Introspect(self):
        """Provide introspection data."""
        return '''<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
  <interface name="org.freedesktop.DBus.ObjectManager">
    <method name="GetManagedObjects">
      <arg type="a{oa{sa{sv}}}" direction="out"/>
    </method>
  </interface>
  <interface name="com.canonical.UbuntuAdvantage.Manager">
    <method name="Attach">
      <arg type="s" direction="in"/>
    </method>
    <method name="Detach"/>
    <method name="GetStatus">
      <arg type="s" direction="out"/>
    </method>
  </interface>
</node>'''


if __name__ == '__main__':
    try:
        syslog.openlog('ua-dbus-stub', syslog.LOG_PID, syslog.LOG_DAEMON)
        dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
        bus = dbus.SystemBus()
        bus_name = dbus.service.BusName('com.canonical.UbuntuAdvantage', bus)
        
        # Register both the root ObjectManager and the Manager object
        root_manager = UbuntuAdvantageObjectManager(bus_name)
        manager = UbuntuAdvantageManager(bus_name)
        
        syslog.syslog(syslog.LOG_INFO, "UA D-Bus stub started successfully")
        mainloop = GLib.MainLoop()
        syslog.syslog(syslog.LOG_INFO, "Entering main loop")
        mainloop.run()
    except KeyboardInterrupt:
        syslog.syslog(syslog.LOG_INFO, "Shutting down")
        sys.exit(0)
    except Exception as e:
        syslog.syslog(syslog.LOG_ERR, f"Fatal error: {e}")
        sys.exit(1)
